### ISSUE TITLE
The prerequisites fulfilled. The project code doesn't work

### ISSUE THREAD

**Issue by minimen456** [usama093/tensorflow-open_nsfw#1]
I've installed Python 3.6.9 and TensorFlow 1.12.0 according to the prerequisites. The project's code doesn't work:
![image](https://user-images.githubusercontent.com/50522449/67162721-d57e6900-f377-11e9-9f99-17fc531b0c10.png)

**Comment by usama093** [comment]
What I understand from the error is that it has to do with Numpy version. Please try downgrading your Numpy version to 1.16.2. It seems to solve the problem.

**Comment by minimen456** [comment]
Thank you for the project. I've fixed the issue by editing line 30 in model.py:
`self.weights = np.load(weights_path, encoding="latin1").item()`
change to
`self.weights = np.load(weights_path, encoding="latin1", allow_pickle=True).item()`
The issue is explaned [here ](https://numpy.org/devdocs/reference/generated/numpy.load.html)
